### ISSUE TITLE
Is it possible to get tighter collision meshes?

### ISSUE THREAD

**Issue by andyp123** [andyp123/blender_vhacd#1]
Currently the collision meshes returned from VHACD are a bit on the "baggy" side of things. Is it possible to adjust settings and get a tighter collision by adjusting the settings? Should the default settings be changed?

**Comment by Hexodus** [comment]
Just select all the collision meshes, go to edit mode, then hit 's' for size and resize to the tightness you prefere.

**Comment by JonasMolgaard** [comment]
I also think the collisions are not excact. I've tried running it with all at maximum settings, and still get collision bodies that don't fit the basemesh very well. Any way to improve it? Im looking for something that is almost 1:1 with the original mesh. As an example, i have this rock, that i want to generate collisions for, and no matter what, i can't get it to generate more than about 35 hulls, and since its a rather big rock, the hulls don't fit the mesh very well.
![Capture](https://user-images.githubusercontent.com/22767628/80627890-dc85e280-8a50-11ea-8586-ba80fd97a5e7.PNG)

**Comment by andyp123** [comment]
To be honest, I don't understand how VHACD works at all. I simply ported the add-on to Blender 2.80.

I have a lot of the same issues as you are experiencing, with the hulls not being close enough to the original mesh, and many wasted triangles where the algorithm is trying to preserve a detail that doesn't matter. I think it's really designed to make quick, rough hulls for physics simulations, but if you want very good and tight hulls then there might be a better algorithm out there, or you can try manually generating them.

For manual generation, I would first split up the most obviously non-convex parts of the mesh into chunks, then using a combination of decimate and convex hull on them to reduce the poly count and make convex shapes. You can then use the rename hulls operator of this add-on to rename the hulls (if you are using them in a game engine such as UE4, then you'll need to do this).

Sorry for this non-solution, but as I said, I didn't make the original algorithm and this add-on is merely a port of the old one which allows you to use VHACD inside of blender.

**Comment by JonasMolgaard** [comment]
Thanks for getting back to me, and i fully understand. Your suggested solution was also what i ended up with, but it is quite timeconsuming (or i suck at Blender hehe). I used the plugin in the 2.78 version, and seem to recall that it was working differently.  I often got over 500 hulls, which i cant seem to get the more recent version to do. Maybe something was changed in the algorithm. I may look into it myself too, but im in a similar situation as you. I dont know how the algorithm works. Anyway will comment here again if i manage to find something.
