### ISSUE TITLE
Possible to get multiple hulls for a single fully convex object?

### ISSUE THREAD

**Issue by geocosmite** [andyp123/blender_vhacd#5]
I am running into a problem with poor collision hull representation for objects that have largely convex shapes.  

As an extreme example consider the case of a sphere.  When using V-HACD on a high resolution spherical mesh but limiting the vertex count to 64 (as is needed for GPU collisions in PhysX for example), what happens for me is that no matter what settings I use I always get just one convex hull that has a surface that is largely within the original sphere's bounds.  In the image below for instance notice the gap between an icosphere in orange and the associated convex hull in black.  The magenta arrow indicates a location where the sphere's surface extends a significant distance beyond the outer edge of the convex hull as indicated by the yellow arrow.

![image](https://user-images.githubusercontent.com/25803192/75077595-7e70d800-54c0-11ea-80cf-7fe311c9891f.png)

In principle the sphere could be represented with greater fidelity if we used multiple convex hulls rather than just one (e.g., 10 hulls could provide 10 times the maximum resolution).  

In my application the objects that I am working with are not spheres although they do suffer from the same problem illustrated here.  

Is anyone aware if V-HACD has a built-in mechanism for allowing multiple convex hulls to be applied to a single convex region?  

Here by, the way, is the configuration I used for the example:
![image](https://user-images.githubusercontent.com/25803192/75077835-1c64a280-54c1-11ea-9e62-8166082cd7e1.png)

Many thanks in advance for your advice (and patience with me if I am missing something that should be obvious!).

**Comment by andyp123** [comment]
Sorry, I'm not really an expert on the V-HACD algorithm - I just ported the old 2.7x version of the Blender addon to 2.80. V-HACD is quite tricky to get to produce very optimal results in many cases, and I've struggled with it a lot myself to be honest.

**Comment by geocosmite** [comment]
Thanks very much for your reply.  One labor intensive workaround I've used is to slice up the object of interest into separate pieces (for instance using xy, xz, and yz planes), fit collision hulls for each piece, and then combine the resulting hulls.

**Comment by andyp123** [comment]
Yes, I've done things like that too, although in that case I often just use Blender's built in convex operator, since it uses the original vertices and fits more tightly.

I don't know if you are using these meshes for a game engine, but in the case of Unreal Engine you can also just make a low poly version of the mesh and assign it to the highest LOD and set the screen size to 0 so it is used for collision but is never rendered. I think convex meshes are still more performant, but even with tools like V-HACD, it can be time consuming to make them when you can't find the right settings.

Anyway, sorry I can't be of more help.
